cassandra:
  image: cassandra:latest
  ports:
    - "17000:7000"
    - "17001:7001"
    - "17199:7199"
    - "19042:9042"
    - "19160:9160"
  volumes:
    - /srv/docker/cassandra:/var/lib/cassandra/data

